apiVersion: v1
kind: Service
metadata:
  name: shop-api-gateway-service
  labels:
    app: shop-api-gateway-service
spec:
  selector:
    app: shop-api-gateway-service
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: NodePort
