name: Dockerize API Gateway Service and Deploy to GKE

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: autopilot-cluster-1
  GAR_LOCATION: us-central1
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: shop-api-gateway-service

jobs:
  docker:
    name: Build, Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Build and push to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/shop-api-gateway-service

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: docker
    environment: production
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Get the GKE Credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - name: Deploy to GKE Cluster
        run: |-
          kubectl delete -f ./k8s/deployment.yml && kubectl apply -f ./k8s/deployment.yml
          kubectl apply -f ./k8s/service.yml
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
