name: Dockerize api gateway service

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build -t '${{secrets.DOCKER_HUB_USERNAME}}'/shop-api-gateway:'${{github.sha}}' .

      - name: Docker login
        run: docker login --username '${{secrets.DOCKER_HUB_USERNAME}}' --password '${{secrets.DOCKER_HUB_PASSWORD}}'

      - name: Push docker image to dockerhub
        run: docker push '${{secrets.DOCKER_HUB_USERNAME}}'/shop-api-gateway:'${{github.sha}}'
